package com.axolotls.prachetaseller.helper;

public class Constant {
    //MODIFICATION PART

    public static final String BASE_URL = "https://pracheta.co/admin/"; //Admin panel url with it whould be nessesary to put "/"(slash) at end of the url (https://admin.panel.url/)

    //set your jwt secret key here...key must same in PHP and Android
    public static final String JWT_KEY = "pra123@_12@_!*_app_34@04_re_rcheta123";

    public static final int LOAD_ITEM_LIMIT = 10; //Load items limit in listing ,Maximum load item once

    //MODIFICATION PART END

    public static final String SUB_URL = "seller/";
    public static final String MAIN_URL = BASE_URL + SUB_URL + "api/api-v1.php";
    public static final String SELLER_POLICY = BASE_URL + "manager-app-play-store-privacy-policy.php";
    public static final String SELLER_TERMS = BASE_URL + "manager-app-play-store-terms-conditions.php";
    public static final String AccessKey = "accesskey";
    public static final String AccessKeyVal = "90336";
    public static final String AUTHORIZATION = "Authorization";
    public static final String GetVal = "1";
    public static final String LOGIN = "login";
    public static final String GET_REQUESTS = "get_requests";
    public static final String SEND_REQUEST = "send_request";
    public static final String CURRENCY = "currency";
    public static final String GET_CATEGORIES = "get_categories";
    public static final String DELETE_OTHER_IMAGES = "delete_other_images";
    public static final String DELETE_VARIANT_IMAGES = "delete_variant_images";
    public static final String DELETE_VARIANT = "delete_variant";
    public static final String UPDATED_BALANCE = "updated_balance";
    public static final String PRODUCT_ID = "product_id";
    public static final String CATEGORY_ID = "category_id";
    public static final String CUSTOMER_PRIVACY = "customer_privacy";
    public static final String LOGO = "logo";
    public static final String VIEW_ORDER_OTP = "view_order_otp";
    public static final String ASSIGN_DELIVERY_BOY = "assign_delivery_boy";
    public static final String SERVE_FOR = "serve_for";
    public static final String STOCK = "stock";
    public static final String LOOSE_STOCK = "loose_stock";
    public static final String STOCK_UNIT_ID = "stock_unit_id";
    public static final String LOOSE_STOCK_UNIT_ID = "loose_stock_unit_id";
    public static final String DESCRIPTION = "description";
    public static final String RETURN_DAYS = "return_days";
    public static final String RETURN_STATUS = "return_status";
    public static final String CANCELABLE_STATUS = "cancelable_status";
    public static final String TILL_STATUS = "till_status";
    public static final String DELIVERY_PLACES = "delivery_places";
    public static final String SUB_CATEGORY_ID = "subcategory_id";
    public static final String TAX_ID = "tax_id";
    public static final String MANUFACTURER = "manufacturer";
    public static final String MADE_IN = "made_in";
    public static final String GET_ORDERS = "get_orders";
    public static final String GET_PRODUCTS = "get_products";
    public static final String UPDATE_ORDER_STATUS = "update_order_status";
    public static final String GET_DELIVERY_BOYS = "get_delivery_boys";
    public static final String TOTAL_ORDERS = "total_orders";
    public static final String TOTAL_PRODUCTS = "total_products";
    public static final String TOTAL_SALE = "total_sale";
    public static final String TOTAL_SOLD_OUT_PRODUCTS = "total_sold_out_products";
    public static final String TOTAL_LOW_STOCK_COUNT = "total_low_stock_count";
    public static final String ORDER_ID = "order_id";
    public static final String ORDER_ITEM_ID = "order_item_id";
    public static final String MESSAGE = "message";
    public static final String FROM = "from";
    public static final String ID = "id";
    public static final String TYPE_ID = "type_id";
    public static final String PRODUCT_VARIANT_ID = "product_variant_id";
    public static final String SELLER_ID = "seller_id";
    public static final String SELLER = "seller";
    public static final String AMOUNT = "amount";
    public static final String GET_UNITS = "get_units";
    public static final String GET_TAXES = "get_taxes";
    public static final String GET_PINCODES = "get_pincodes";
    public static final String PINCODES = "pincodes";
    public static final String INDICATOR = "indicator";
    public static final String IMAGE = "image";
    public static final String VARIANT_ID = "variant_id";
    public static final String TYPE = "type";
    public static final String MEASUREMENT = "measurement";
    public static final String MEASUREMENT_UNIT_ID = "measurement_unit_id";
    public static final String PRICE = "price";
    public static final String DISCOUNTED_PRICE = "discounted_price";
    public static final String OTHER_IMAGES = "other_images[]";
    public static final String VARIANT_OTHER_IMAGES = "images";
    public static final String ADD_PRODUCTS = "add_products";
    public static final String UPDATE_PRODUCTS = "update_products";
    public static final String NAME = "name";
    public static final String STORE_NAME = "store_name";
    public static final String EMAIL = "email";
    public static final String MOBILE = "mobile";
    public static final String PASSWORD = "password";
    public static final String DATA = "data";
    public static final String STATUS = "status";
    public static final String DELIVERY_BOY_ID = "delivery_boy_id";
    public static final String CHANGE_STATUS = "change_status";
    public static final String FCM_ID = "fcm_id";
    public static final String OFFSET = "offset";
    public static final String LIMIT = "limit";
    public static final String SHOW = "show";
    public static final String HIDE = "hide";
    public static final String ERROR = "error";
    public static final String TOTAL = "total";
    public static final String SEARCH = "search";
    public static final String GET_CUSTOMERS = "get_customers";
    public static final String BALANCE = "balance";
    public static String SETTING_CURRENCY_SYMBOL = "";
    public static String SOLDOUT_TEXT = "Sold Out";
    public static String LOW_STOCK_TEXT = "Low Stock";
    public static String ALL = "all";
    public static String RECEIVED = "received";
    public static String PROCESSED = "processed";
    public static String SHIPPED = "shipped";
    public static String DELIVERED = "delivered";
    public static String CANCELLED = "cancelled";
    public static String RETURNED = "returned";
    public static String AWAITING_PAYMENT = "awaiting_payment";
    public static String SOLDOUT = "out_stock";
    public static String LOWSTOCK = "low_stock";
    public static CharSequence[] filtervalues = {ApiConfig.toTitleCase(ALL), SOLDOUT_TEXT, LOW_STOCK_TEXT};
    public static String NEW = "new";
    public static String OLD = "old";
    public static String HIGH = "high";
    public static String LOW = "low";
    public static String SORT = "sort";
    public static CharSequence[] sortvalues = {" Newest to Oldest ", " Oldest to Newest ", " Price Highest to Lowest ", " Price Lowest to Highest "};
    public static String FILTER = "filter";
    public static String IS_USER_LOGIN = "is_user_login";
    public static String GET_FINANCIAL_STATISTICS = "get_financial_statistics";
    public static String GET_SELLER_BY_ID = "get_seller_by_id";
    public static String UPDATE_SELLER_FCM_ID = "update_admin_fcm_id";
    public static String PRODUCT_LOAD_LIMIT = "10";
}
